# Generated by Django 5.0.6 on 2024-06-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_user_delete_usertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(),
        ),
    ]
