# Generated by Django 5.0.6 on 2024-06-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_task_deadline_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
